# .streamlit/config.toml

# Additional configuration for customizing the app
[theme]
base = "dark"  # Options: "dark" or "light"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"  # Available options: "sans serif", "serif", "monospace"
